	.z80
	cseg
;;;;ST0tble	equ	0fa7ah	; must check version first
bdos	equ	00005h

start:	ld	e,0ffh
	ld	c,06h		; BDOS Direct console i/o
	call	bdos
	ld	c,0
	or	a		; test if character entered
	jp	nz,bdos		; -yes- so quit

	ld	de,st0tble
	ld	hl,copy
	ld	b,8
test:	ld	a,(de)
	cp	(hl)
	ld	(hl),a
	jr	nz,print
	inc	hl
	inc	de
	djnz	test
	jr	start

print:	ld	e,0ah		; <line feed>
	ld	c,06h		; BDOS Direct console i/o
	call	bdos

	ld	hl,ST0tble
	ld	b,4
	ld	c,2
next:	push	bc
	ld	a,(hl)
	push	hl
	rrca
	rrca
	rrca
	rrca
	call	hex
	pop	hl
	ld	a,(hl)
	push	hl
	call	hex

	ld	e,' '
	ld	c,06h		; BDOS Direct console i/o
	call	bdos

	pop	hl
	pop	bc
	inc	hl
	dec	c
	jr	nz,next
	ld	c,2
	push	bc
	push	hl

	ld	e,' '
	ld	c,06h		; BDOS Direct console i/o
	call	bdos

	pop	hl
	pop	bc
	djnz	next

	ld	e,0dh		; <return>
	ld	c,06h		; BDOS Direct console i/o
	call	bdos

	jp	start

hex:	and	0fh
	add	a,'0'
	cp	'9'+1
	jr	c,hexchr
	add	a,'A'-'0'-10
hexchr:	ld	e,a
	ld	c,06h		; BDOS Direct console i/o
	jp	bdos

copy:	db	0,0,0,0,0,0,0,0

	end
